--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#fff5f3"
foreground="#4d696f"
cursor="#4d696f"

-- Colors
color0="#fff5f3"
color1="#df2014"
color2="#587d0a"
color3="#8a6f00"
color4="#196bec"
color5="#c83884"
color6="#2a79a2"
color7="#4d696f"
color8="#8b6781"
color9="#9a511a"
color10="#11742f"
color11="#8d590a"
color12="#004fff"
color13="#9536c0"
color14="#046c92"
color15="#4d696f"
