# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#fff5f3'
foreground='#4d696f'
cursor='#4d696f'

# Colors
color0='#fff5f3'
color1='#df2014'
color2='#587d0a'
color3='#8a6f00'
color4='#196bec'
color5='#c83884'
color6='#2a79a2'
color7='#4d696f'
color8='#8b6781'
color9='#9a511a'
color10='#11742f'
color11='#8d590a'
color12='#004fff'
color13='#9536c0'
color14='#046c92'
color15='#4d696f'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
